{
# 公众号配置
# 公众号appId
"wxb8b020dbca8626a0",
# 公众号appSecret
"6664b30557ed5f02a714ead19a28cac8",
# 模板消息id
"	He8JM5AtJVzrCb0HNHZ5FV7subU6y5c6HXTTZlUQdY8",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
["oZJkj6eBdSirbycdUp1b2XJBlwi4"],

# 信息配置
# 和风天气apikey
"b13a26d0d7a3461f91a921d75dc5859c",
# 天行数据apikey
"c60461016b9eaa1c6c24d9c8b4bb335d",
# 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦(国外城市可能获取不到pm2.5，空气质量，今日建议等数据)
"卧龙区",
# 生日1
{"蓓蓓", "2002-02-23"},
# 生日2
{"鹤鹤", "2004-09-11"},
# 在一起的日子，格式同上
"2022-10-01",
# 金句中文，如果为空，默认会读取金山的每日金句
"note_ch": "",
# 金句英文
"note_en": ""
}
